In [1]:
import numpy as np


In [3]:
my_arr = np.arange(1000000)


In [4]:
my_list = list(range(1000000))


In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2


CPU times: user 4.96 ms, sys: 36.3 ms, total: 41.3 ms
Wall time: 41.6 ms


In [6]:
%time for _ in range(10): my_list2 = my_list * 2


CPU times: user 199 ms, sys: 28 ms, total: 227 ms
Wall time: 225 ms


# difference

Numpy-based algorithms are generally 10 to 100 times faster (or more) than their pure Python counterparts and use significantly less memory.

# 4.1 The Numpy ndarray: A multidimensional Array Object

In [8]:
import numpy as np

In [9]:
# Generate some random data
data = np.random.randn(2, 3)

In [11]:
data

array([[ 0.23304987, -0.27302648,  0.51698349],
       [ 1.20940156, -0.21088058, -0.63070072]])

In [12]:
data * 10

array([[ 2.3304987 , -2.73026475,  5.16983488],
       [12.0940156 , -2.10880583, -6.30700724]])

In [13]:
data + data

array([[ 0.46609974, -0.54605295,  1.03396698],
       [ 2.41880312, -0.42176117, -1.26140145]])

**Every array has a shape, a tuple indicating the size of each dimension, and a dimension, and a dtype, an object describing the data type of the array:**

In [14]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

## Creating ndarrays

Using *array* function. This accepts any sequence-like object. For example, a list is a good candidate for conversion:

In [2]:
data1 = [6, 7.5, 1, 2, 22]

In [3]:
arr1 = np.array(data1)

In [4]:
arr1.dtype

dtype('float64')

In [5]:
arr1.shape

(5,)

In [6]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [7]:
arr2 = np.array(data2)

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.min()

1

In [10]:
arr2.max()

8

In [11]:
arr2.ndim

2

In [12]:
arr1.dtype

dtype('float64')

In [13]:
arr2.dtype

dtype('int64')

*zeros* and *ones* create arrays of 0s or 1s. To create o higher dimensional array with these methods, pass a tuple for the shape:

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.empty((2, 3, 2))

array([[[6.94218853e-310, 6.94222536e-310],
        [6.94218853e-310, 6.94218853e-310],
        [6.94218853e-310, 6.94222825e-310]],

       [[6.94222492e-310, 6.94218848e-310],
        [6.94218848e-310, 6.94222550e-310],
        [6.94218848e-310, 6.94218848e-310]]])

## Data Types for ndarrays

The **dype** is a special object containing in the information (or, *metadata*, data about data) the ndarray needs to interpret a chunk of memory as a particular type of data:

In [19]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [20]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [21]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int32')

You can explicitly convert or *cast* an array from one dtype to another using ndarray's astype method:

In [2]:
arr = np.array([1, 2, 3, 4, 5])

In [3]:
arr.dtype

dtype('int64')

In [4]:
float_arr = arr.astype(np.float64)

In [5]:
float_arr.dtype

dtype('float64')

In [7]:
float_arr

array([1., 2., 3., 4., 5.])

If you have an array of strings representing numbers, you can use astype to convert them to numeric form:

In [13]:
numeric_strings = np.array(["1.2", "-9.2", "42"], dtype=np.string_)

In [14]:
numeric_strings.astype(float)

array([ 1.2, -9.2, 42. ])

Calling the **astype** always creates a new array( a copy of the data), even if the new type is the same as the old type.

## Arithmetic with NumPy Arrays

Numpy has an important feature called vectorization. Any arithmetic operations between equal-size arrays applies the operation element-wise:

In [15]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [16]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [18]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [21]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [22]:
arr2 = np.array([[0.0, 4, 2], [7.0, 2.0, 12.0]])

In [23]:
arr2

array([[ 0.,  4.,  2.],
       [ 7.,  2., 12.]])

In [25]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

One-dimensional arrays are simple; on the surface they act similarly to Python lists:

In [26]:
arr = np.arange(10)

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[5]

5

In [29]:
arr[5:8]

array([5, 6, 7])

In [30]:
arr[5:8] = 12

In [31]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

This means that the data is not copied, and any modifications to the view will be reflected in the source array.

In [32]:
arr_slice = arr[5:8]

In [33]:
arr_slice

array([12, 12, 12])

Now, when I change values in arr_slice, the mutations are reflected in the original array arr:

In [34]:
arr_slice[1] = 12345

In [36]:
arr_slice

array([   12, 12345,    12])

In [37]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

The "bare" slice[:] will assign to all values in an array:

In [38]:
arr_slice[:] = 64

In [39]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

With higher dimensional arrays:

In [68]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [69]:
arr2d[2]

array([7, 8, 9])

you can pass a comma-separated list of indices to select individual elements.

In [70]:
arr2d[0][2]

3

equals to: 

In [47]:
arr2d[0, 2]

3

If you want a copy of a slice of an ndarray instead of a view, you will need to explictly copy the array-for example, arr[5:8].copy()

In [82]:
arr = np.array(range(10))

In [83]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
arr2 = arr[5:8]

In [93]:
arr2 is arr[5:8]

False

In [94]:
arr2 == arr[5:8]

array([ True,  True,  True])

In multidimensional arrays, If you omit later indices, the retured object will be a low dimensional ndarray consisting of all the data along the higher dimensions. 

In [95]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [97]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

arr3d[0] is a 2 * 3 array:

In [98]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

### Indexing with slices

In [104]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Consider the two-dimensional array, it has sliced along axis 0, the first axis. It can be helpful to read the expression arr2d[:2] as **"select the first two rows of arr2d."**

In [105]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

You can pass multiple slices just like you can pass multiple indexes:

In [106]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

By mixing integer indexes and slices, you get lower dimensional slices.

In [107]:
arr2d[1, :2]

array([4, 5])

In [108]:
arr2d[:2, 2]

array([3, 6])

Note that a colon by itself means to take the entire axis, so you can slice only higher dimensional axes by doing:

In [119]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

array([[1],
       [4],
       [7]])

## Boolean Indexing
Let's consider an example where we have some data in an array and an array of names with duplicates

In [124]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [125]:
data = np.random.randn(7, 4)

In [126]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [127]:
data

array([[-1.25879148, -0.47455288, -0.79487084, -0.2024177 ],
       [ 0.74614545,  1.34564145, -0.56508326,  1.4631497 ],
       [-0.1757532 ,  0.98229635,  0.45227742,  0.3860729 ],
       [ 0.66671407,  0.19303851,  0.67934542, -1.28820116],
       [-0.17342215,  0.24409039, -1.20518031,  1.72527569],
       [ 0.16601936,  1.78389888, -0.29026128,  1.01194477],
       [-1.45966601,  0.87680734, -0.00871364,  0.03431714]])

Suppose each name corresponds to a row in the data array and we wanted to select all the rows with corresponding name 'Bob'.

In [128]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [129]:
data[names == 'Bob']

array([[-1.25879148, -0.47455288, -0.79487084, -0.2024177 ],
       [ 0.66671407,  0.19303851,  0.67934542, -1.28820116]])

Boolean selection will not fall if the boolean array is not the correct length,  so be careful when using this feature.

In [140]:
data[names == "Bob", 2:]

array([[-0.79487084, -0.2024177 ],
       [ 0.67934542, -1.28820116]])

In [141]:
data[names == 'Bob', 3]

array([-0.2024177 , -1.28820116])

In [142]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [143]:
~(names == 'Bob')

array([False,  True,  True, False,  True,  True,  True])

In [145]:
data[~(names == 'Bob')]

array([[ 0.74614545,  1.34564145, -0.56508326,  1.4631497 ],
       [-0.1757532 ,  0.98229635,  0.45227742,  0.3860729 ],
       [-0.17342215,  0.24409039, -1.20518031,  1.72527569],
       [ 0.16601936,  1.78389888, -0.29026128,  1.01194477],
       [-1.45966601,  0.87680734, -0.00871364,  0.03431714]])

The ~ operator can be useful when you want to invert a general condition:

In [146]:
cond = names == 'Bob'

In [147]:
data[~cond]

array([[ 0.74614545,  1.34564145, -0.56508326,  1.4631497 ],
       [-0.1757532 ,  0.98229635,  0.45227742,  0.3860729 ],
       [-0.17342215,  0.24409039, -1.20518031,  1.72527569],
       [ 0.16601936,  1.78389888, -0.29026128,  1.01194477],
       [-1.45966601,  0.87680734, -0.00871364,  0.03431714]])

Selecting two of the three names to combine multiple boolean conditions, use boolean arithmetic operator like & and |:

In [149]:
mask = (name == "Bob") | (names == "Will")

In [150]:
mask

array([ True, False,  True,  True,  True, False, False])

In [152]:
data[mask]

array([[-1.25879148, -0.47455288, -0.79487084, -0.2024177 ],
       [-0.1757532 ,  0.98229635,  0.45227742,  0.3860729 ],
       [ 0.66671407,  0.19303851,  0.67934542, -1.28820116],
       [-0.17342215,  0.24409039, -1.20518031,  1.72527569]])

Selecting data from an array by boolean indexing **always** creates a copy of the data, even if the returned array is unchanged.

In [153]:
data < 0

array([[ True,  True,  True,  True],
       [False, False,  True, False],
       [ True, False, False, False],
       [False, False, False,  True],
       [ True, False,  True, False],
       [False, False,  True, False],
       [ True, False,  True, False]])

Setting values with boolean arrays works in a common-sense way. To set all of the negative values in data to 0 we need only do:

In [154]:
data[data < 0] = 0

In [155]:
data

array([[0.        , 0.        , 0.        , 0.        ],
       [0.74614545, 1.34564145, 0.        , 1.4631497 ],
       [0.        , 0.98229635, 0.45227742, 0.3860729 ],
       [0.66671407, 0.19303851, 0.67934542, 0.        ],
       [0.        , 0.24409039, 0.        , 1.72527569],
       [0.16601936, 1.78389888, 0.        , 1.01194477],
       [0.        , 0.87680734, 0.        , 0.03431714]])

## Fancy Indexing

*Fancy Indexing* is a term to describe indexing using integer arrays.

In [161]:
arr = np.empty((8, 4))

In [162]:
for i in range(8):
    arr[i] = i

In [163]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

To select out a subset of the rows in a particular order, you can simply pass a list or ndarray of integers specifying the desired order:

In [174]:
arr[[4, 5, 2, 7]]

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [2., 2., 2., 2.],
       [7., 7., 7., 7.]])

In [175]:
arr[[-3, -5, 7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

Passing multiple index arrays does something slightly different; it selects a one-dimensional array of elements corresponding to each tuple of indices.

In [188]:
arr = np.arange(32).reshape((8, 4))

In [189]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [190]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

Here the elements (1, 0), (5, 3), (7, 1) and (2, 2) were selected.

Keep in mind that fancy indexing, unlike slicing, always copies the data into a new array.

## Transposing Arrays and Swapping Axes 