In [1]:
import numpy as np

In [3]:
my_arr = np.arange(1000000)

In [4]:
my_list = list(range(1000000))

In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 4.96 ms, sys: 36.3 ms, total: 41.3 ms
Wall time: 41.6 ms


In [6]:
%time for _ in range(10): my_list2 = my_list * 2

CPU times: user 199 ms, sys: 28 ms, total: 227 ms
Wall time: 225 ms


# difference

Numpy-based algorithms are generally 10 to 100 times faster (or more) than their pure Python counterparts and use significantly less memory.

# 4.1 The Numpy ndarray: A multidimensional Array Object

In [8]:
import numpy as np

In [9]:
# Generate some random data
data = np.random.randn(2, 3)

In [11]:
data

array([[ 0.23304987, -0.27302648,  0.51698349],
       [ 1.20940156, -0.21088058, -0.63070072]])

In [12]:
data * 10

array([[ 2.3304987 , -2.73026475,  5.16983488],
       [12.0940156 , -2.10880583, -6.30700724]])

In [13]:
data + data

array([[ 0.46609974, -0.54605295,  1.03396698],
       [ 2.41880312, -0.42176117, -1.26140145]])

**Every array has a shape, a tuple indicating the size of each dimension, and a dimension, and a dtype, an object describing the data type of the array:**

In [14]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

## Creating ndarrays

Using *array* function. This accepts any sequence-like object. For example, a list is a good candidate for conversion:

In [2]:
data1 = [6, 7.5, 1, 2, 22]

In [3]:
arr1 = np.array(data1)

In [4]:
arr1.dtype

dtype('float64')

In [5]:
arr1.shape

(5,)

In [6]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [7]:
arr2 = np.array(data2)

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.min()

1

In [10]:
arr2.max()

8

In [11]:
arr2.ndim

2

In [12]:
arr1.dtype

dtype('float64')

In [13]:
arr2.dtype

dtype('int64')

*zeros* and *ones* create arrays of 0s or 1s. To create o higher dimensional array with these methods, pass a tuple for the shape:

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.empty((2, 3, 2))

array([[[6.94218853e-310, 6.94222536e-310],
        [6.94218853e-310, 6.94218853e-310],
        [6.94218853e-310, 6.94222825e-310]],

       [[6.94222492e-310, 6.94218848e-310],
        [6.94218848e-310, 6.94222550e-310],
        [6.94218848e-310, 6.94218848e-310]]])

## Data Types for ndarrays

The **dype** is a special object containing in the information (or, *metadata*, data about data) the ndarray needs to interpret a chunk of memory as a particular type of data:

In [19]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [20]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [21]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int32')

You can explicitly convert or *cast* an array from one dtype to another using ndarray's astype method:

In [2]:
arr = np.array([1, 2, 3, 4, 5])

In [3]:
arr.dtype

dtype('int64')

In [4]:
float_arr = arr.astype(np.float64)

In [5]:
float_arr.dtype

dtype('float64')

In [7]:
float_arr

array([1., 2., 3., 4., 5.])

If you have an array of strings representing numbers, you can use astype to convert them to numeric form:

In [13]:
numeric_strings = np.array(["1.2", "-9.2", "42"], dtype=np.string_)

In [14]:
numeric_strings.astype(float)

array([ 1.2, -9.2, 42. ])

Calling the **astype** always creates a new array( a copy of the data), even if the new type is the same as the old type.

## Arithmetic with NumPy Arrays

Numpy has an important feature called vectorization. Any arithmetic operations between equal-size arrays applies the operation element-wise:

In [15]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [16]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [18]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [21]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [22]:
arr2 = np.array([[0.0, 4, 2], [7.0, 2.0, 12.0]])

In [23]:
arr2

array([[ 0.,  4.,  2.],
       [ 7.,  2., 12.]])

In [25]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

One-dimensional arrays are simple; on the surface they act similarly to Python lists:

In [26]:
arr = np.arange(10)

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[5]

5

In [29]:
arr[5:8]

array([5, 6, 7])

In [30]:
arr[5:8] = 12

In [31]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

This means that the data is not copied, and any modifications to the view will be reflected in the source array.

In [32]:
arr_slice = arr[5:8]

In [33]:
arr_slice

array([12, 12, 12])

Now, when I change values in arr_slice, the mutations are reflected in the original array arr:

In [34]:
arr_slice[1] = 12345

In [36]:
arr_slice

array([   12, 12345,    12])

In [37]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

The "bare" slice[:] will assign to all values in an array:

In [38]:
arr_slice[:] = 64

In [39]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

With higher dimensional arrays:

In [40]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [41]:
arr2d[2]

array([7, 8, 9])

you can pass a comma-separated list of indices to select individual elements.

In [45]:
arr2d[0][2]

3

equals to: 

In [47]:
arr2d[0, 2]

3

In [48]:
%pwd

'/home/jay/Programming'